# Generated by Django 5.2.6 on 2025-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
