# Generated by Django 5.2.6 on 2025-09-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant logo or image', null=True, upload_to='restaurant_logos/'),
        ),
    ]
