# Generated by Django 5.2.6 on 2025-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(blank=True, default='30-45 minutes', help_text='Estimated delivery time', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Restaurant email', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_description',
            field=models.TextField(blank=True, default='Discover amazing food from top restaurants in your area. Fresh ingredients, great taste, and fast delivery.', help_text='Hero description for meal list page'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for meal list page', null=True, upload_to='restaurant_heroes/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hero_title',
            field=models.CharField(blank=True, default='Delicious Meals', help_text='Hero title for meal list page', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(blank=True, default='Mon-Sun: 9:00 AM - 10:00 PM', help_text='Restaurant opening hours', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Restaurant phone number', max_length=20),
        ),
    ]
