# Generated by Django 5.2.6 on 2025-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_description_alter_meal_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='prep_time_max',
            field=models.PositiveIntegerField(default=20, help_text='Maximum preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='meal',
            name='prep_time_min',
            field=models.PositiveIntegerField(default=15, help_text='Minimum preparation time in minutes'),
        ),
    ]
