# Generated by Django 5.2.6 on 2025-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FoodOrdering', help_text='The name of your platform', max_length=100)),
                ('site_description', models.TextField(default='Your favorite food delivery platform', help_text='Brief description of your platform')),
                ('site_logo', models.ImageField(blank=True, help_text='Platform logo', null=True, upload_to='platform/logos/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Platform favicon', null=True, upload_to='platform/favicons/')),
                ('contact_email', models.EmailField(default='admin@foodordering.com', help_text='Main contact email', max_length=254)),
                ('support_phone', models.CharField(default='+1 (555) 123-4567', help_text='Support phone number', max_length=20)),
                ('support_email', models.EmailField(default='support@foodordering.com', help_text='Support email', max_length=254)),
                ('company_address', models.TextField(default='123 Food Street, City, State 12345', help_text='Company address')),
                ('business_hours', models.CharField(default='Mon-Sun: 9:00 AM - 10:00 PM', help_text='Business hours', max_length=100)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=2.99, help_text='Default delivery fee', max_digits=5)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=25.0, help_text='Minimum order for free delivery', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=8.5, help_text='Tax rate percentage', max_digits=5)),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow new user registration')),
                ('allow_restaurant_registration', models.BooleanField(default=True, help_text='Allow new restaurant registration')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('meta_title', models.CharField(default='FoodOrdering - Delicious Food Delivery', help_text='SEO meta title', max_length=60)),
                ('meta_description', models.TextField(default='Order delicious food from top restaurants in your area. Fast delivery, great taste!', help_text='SEO meta description')),
                ('meta_keywords', models.CharField(default='food delivery, restaurant, order online', help_text='SEO meta keywords', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
